branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: Cohesion
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: PHP 7.1
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: CohesionAPI
  sc: git
  workspace_type: Application
